farm_map = """YYYYYYYYYYYYYYYYYYYYYYYGGGGGGGGGGGSSSSSSSSSSSSSSSSSRRRRRRRZXXXXXUUUUUUUSSRRRRRRRRRRRRRRRRRRRRRRRVVVVVSSSSSSSOOOOOOOOOOOOOOOBBPPPPPPPPPJJJJJJ
YYYDDDYYYYYYYYYYYYYYYYGGGGGGGGGGGXXSSSSSSSSSSSSSSSRRRRRRRRZXXXXUUUUUUUUUURRRRRRRRRRRRRRRRRRRRRRRRVVVGSSSSSSSOOOOOOOOOOOHOOOOPPPPPPPPPJJJJJJJ
YYYDDDDYDYYYYYYYYYYGGYGGGGGGGGGGGXSSSSSSSSSSSSSSSSZRRRZZZZZZXXXUUUUUUUUUUQRRRRRRRRRRRRRRRRRRRRRRRVDGGSSTTTTSOOOOOOOOOOOHHOOOPPPPPPPPPPJJJJJJ
YYYYYDDDDDDDDYYYYYYYGGGGGGGGGGGGGSWSSSSSSSSSSSSSSSZZZZZZZZZZZZZUUUUUUUUUUURRRRRRRRRRRRRRRRRRRRRRGGGGGSTTTTTTOOHOAOOOOOOHHHHHVVPPPPPPQQYYYYJJ
YIIDYYDDDDDDDYYYYYYYGGGGGGGGGGGGSSSSSSSSSSSNNNSNNZZZMZZZZZZZZZZUUUUUUUUUUURRRRRRRRRRRRRRRRRRRRGGGGGGGGTTTTHHHHHOAOAOOOOHNNNHVVPPPPPYQYYYYYYJ
IIIDDYYDDDDDYYYYYYYYYGGGGGGGGGGSSSSSSSSSSSSNNNNNNNZZZZZZZZZZZZUUUUUUUUUUUUUUURRRRRRRRRRRRRRRRRGGGGGGGGTTTTTHHHHOAAAOOOHHHHHHHPPPYYYYYYYYYYYY
IIIDDYDDDDDDDDYYYYYYYYGGGGGGGGGSSSSSSSSSSSNNNNNNNNNNNZZZZZZZZZUUUUUUUUUUUUUUUURRWRRRRRRRRUUGRGGGGGGGGGTTTTTHHHAAAAAOOOHHHHHHHEPPYYYYYYYYYYYY
IIIDDDDDDDDDDYYYYYYYGGGGGGGGGGGGSFSSSSSSSSSNNNNNNNNNNNZUZZZZZZZZUUUUUUUUUUUUUUYYRRRRRRRUUUUGRGGGGGGGGYTTTTTHHHHHHAAOOOHHHHHHHEEYYYYYYYYYYYYY
IIDDDDDDDDDDDYYYYYYGGGGGGGGGGGGGZFSSSSSSSSSSSSNNNNNNNNNNZZZMZZZUUUUUZZZZZZZZZZYYYYRRRRRUUUGGGGGGGGGGGTTTTHHHHHHHHAOOHHHHHHHHHEAAYYYYYYYYYYYY
IIDIIDDDDDDDDYYYYYYGGGGGGGGGGGGTFFFFSSSSSSSSSSNNNNNNNNNNZZMMZZZUUUUUZZZZZZZZZZYYYYYUUUUUUUGGGGGGGGGGHHHTTTHHOOOOOOOOOHHHHHHHHEYYYYYYYYYYYYYY
IIIIIDDDDDDDDYYYYYYYGGGGGGGGGGGGGFFFSLLSSSSSBBNCNNNNNNNNNZMZZZUUUUUUZZZZZZZZZZAAYYYAUUUUUUUUGGGGGGGGHHHHHTHHOOOORROOHHHHNHHEEEEEEYYYYYYYYYYY
IIIIIDDDDDDYDYYYYCYGGUUUGGGGGGGGGFFFFLLLFFPSSSCCCNNNNNNINNMZZPUTTTTUZZZZZZZZZZAAAAAAUUUUUUUGGGGGGGGGGBHHHRHHHHHRRROHHHHNNNNNNEEEEEEYYYYYYYYY
IIIIIIDDDDDYYYYYCCCCCCCGGGGGFFFFFFFFFFFFFFPPSCCCCNNNNNNINMDDDDUDTTTTZZZZZZZZZZAAAAXXUUUUUUUUGGGGGGBBBBHHHRRRRRRRRRRFHHNNNNNNNNEEEEEEEYFYYYYY
IIIIIIIDDDDDYYYCCRCCCCCCOOOFFFFFFFFFFFFFFFFCCCCCCCENNWWIDDDDDDDDTTTZZZZZZZZZZZAAAAXXUUUUUUUUUUGGGBOBBBBRRRRRRRRRRRFFFFNNNNNNNNNEEEEEEXYYYYQQ
IIIIDDDDDDDDDDWQCCCCCCCCCCCFFFFFFFFFFFFFFFFCCCCCCCCNJWWIDDDDDDDDTTTZZZZZZZZZZZAAAAXXUXUTTTUUUUUBNBBBBBRRRRRRRRRRRRRFFNNNNNNNNNNNCEEEEEYQQYQQ
IIIIIDDDDDDSWWWWCCCCCCCCCCCFFFFFFFFFFFFFFCCCCCCCCCCRWWWWDDDDDDDDDDVZZZZZZZZZZZAAAAXXUUUATTTUUTUBNBBBBRRRRRRRRRRRRRPNNNNNNNNNNNNNCEEEEYYYQQQQ
IIIIIIDDSSDSWWWWCCCCCCCCCCCFFFFFFFFFFFFFFCCCCCCCCCCCWWWUDDDDDDDDVVVVZZZZZZZZZZAAAAXXUUUTTTTTTTTBBBBBBBRRRRRRRRRPPPPNNNNNNNNNNNNCCCCEEEQQQYQQ
IIIIIIDDSSSSWWCCCCCCCCCCCCFFFFFFFFFFFGCCCCCCCCCCCCCWWWWWDDDDDDVVVVVVZZZZZZZZZZAAAXXXXXTTTTTTTTTBBBBBBBBRRRRORRRRPPNNNNNNNNNNNNNRCCSCEQQQQYQQ
IIIIIIDSSSSSSSSCCCCCCCCCCCFFFFFFFFFFGGGGCCCCCCCCCCCWWWVVDDDDDDDVVVVVWNNNZZZZZNAAJJJJXTTTTTTHHTTBBBBBBBBRRRRRRRRRPPPNNNNNNNNNNNRRCCCCQQQQYYQQ
IIIIIISSSSSSSSCCCCCCCCCCCZFUFFFFFFFFGGGGGCCCCCCCCCCWWWWVVVVVDDVVVVVVVNNNZZZZZNNNJJJJJTTTTTHHHBBBBBBBBBBRBRTTRRVVRPPNNNNNNNNNNPCCCCCCQQQYYYYQ
IIIIIASSSSSSSSCCCCCCCCCZZZZFFFNFNNFFGGGGGCCCCYCCCCCWWWVVVVVVVDDVVVVVVSSNZZZZZNNNJJJJJJJJTHHHHBBBBBBBBBBBBRTTRRRRRRPPNBNNNNNNNNCCCCCCQQQQQYYQ
IAIAAASSSSSSSRRCCCCCCCCZZZZNNNNNNNCCGGGCCCCCCYCCCOOOOVVVVVVVVDVVVVVVVVSNZZZZZNNNNJJJJJJPTHHHHBBBBBBBBBBBBBBBVEREEEEEBBNNNNNNNCCCCCCQQQQQQYYQ
AAAAAAASSSSSSSCCCCCCCCCCCZNNNNNNNCCCCCCCCCCCCYCOOOOOOOOOVVVVVVVVVVVVVESNZZZZZNNNJJJJJJJJHHHHHBBBBBBBEBBBBBBBVEEEEEEEGGGGYGGNCCCCCCCCCQCQQYQQ
SAAAAAAAAASSSSSCCCCCCCCKCNNNNNNNNCCCCCCCCCYYYYCOOOOOOOOOVVVVVVVVVVVEEEECZZZZZNNJJJJJJJJJJJHHHBBBBBBBBBBBBBBEEEEEEEEEEGGGGGGGGCCCCCCCCCCCQQQQ
AAAAAAAAAAASAIACCCCCCCKKKKNNNNNNNCCCCCCCCCYYYYYOOOOOOOOOVVVVVVVVVVVEEEEEZZZZZJNJJJJJJJJJJJHHHHBAABBBBBBBBBBEEEEEEEEEGGGGGGGGGCCCCCCCCCCCQQQQ
AKAAAAAAAAAAAAAYYCYCYCKTTTTNNTNNXXXCCCCCCYYYYYYOOOOOOOOOVVVVVVVVVEEEEEEEZZZZZJJJJJJJJJJJHHHHHHHBBBBBBBBBBBBBEEEEEEEEEGGGGGGGGCCCCCCCCCCCQQQQ
AAAAAAAAOOAAAAAAYYYYYCCTTTTTTTTXXXXXCYYCVYYYYYYOOOOWWWWWWWWVVVCCCCCEEEEEEJJJJJJJJJJJJJJJHHHHHHHBBBBBBBBBBBBBEEEEEEEEEGGGGGGGGGGCCCCCRRRCQQQQ
NANNAAAAOAAAAAAAYYYYYTMTTTTTTTTTXXXXXYYYYYYYYYYOOOOWWWWWWWWCCCCCCCCEEEEEETJJJJJJJJJJJJEHHHHHHHHHHBBBBBBBBBBEEEEEEEEEEGGGGGGGGGGGCCRRRRRCQQQQ
NNNNAAPPPPPAAAAAYYYYYTTTTTTTTTXXXXXXXXYYYYYYYYYOOOOWWWWWWWWCCCCCCCCCEEEETTJJTJJJJJEJJQEEEHHHHHHHBBBBBBBBBBBEEEEEEEEGGGGGGGGGGGGGBCCRRRJJJQQJ
NNNNAAPPPPPAAAAAYYYYYTTTTTTTTXXXXXXXXKKKDYYYYYYCCOOWWWWWWWWCCCCCCCCCCCCCCTTTTJJJJJEEEEEEEHHHHHHHHBBBBBBBBBBEEEEEEEEEGGGGGGGGGGGBBCCCRJJJJJJJ
NNNNNAPPPPPAAAAAYYYYTTTTTTTTTTXXXXXYKKKKYYYYYYYCCCCWWWWWWWWCCCCCCCCCCCCCTTTTTTTTJJEEEEEEEEEHHHHHBFBBBBBBBBBBEEEEEEEEEEEGGGGGGCCJJJJJJJJJJJJS
NNNNBBPPPPPAAAAPPYYYTTTTTTTTTTXXXXYYYYYKYYYYYYCCCCCWWWWWWWWWWWWCCCCCCCCCTTTTTTTTTTZEEEEEEHHHHWWHBBBBBBBBBBBBEEEEEEEEEEOOGGGGGGJJJJJJJJJJJJJS
NNNNNPPPPPPPAPPPPYYYTTTTTTTTTTXXXXXXXYYYYYYYYYCCCCOWWWWWWWWWWWWCCCCCCCCCTTTTTTTTTZZEEEEEEHWWWWWHBBBBBBBBBBBBKEEEEEEEEEOGGGGGGGGJJJJJJJJJJJJJ
NNNNNNPPPPPPAPPPPPYYYYTTTTTTTTXXXXXXXYYYYYYYYCCCCCOWWWWWWWWWWWWCACCCCCCCCTTTTTTTTEEEEEEEEEPPPWWHHHBHBBBBOOOOEEEEEEEEEOOGGGGYYYYJJJJJJJJJJJJJ
NNNNNNPPPPPPPPPPPYYYYYTTTTTTTTTMMMXMXXYYYYYYYCCYCCOWWWWWWWWWWWAAACCCQTCCTTTTTTTTTJEEEEEEQWWWWWWWHHHHHHBBOEOOSEEEEEEEEESSYYYYYYYJJJJJJJJJJJJJ
NNNNNNNNPPPPPPPPPYYYYYETTTTTTTTMMKMMMMYYYYYYYYYYCCOWWWWWWWWWWWAAACLLTTCTTTTTTTTTJJJJEEEEEWWWWWWWWHHHEEEEEEEOSSSEEEEEEESSSYYYYYYYJJJJJJJJJLLJ
NNNNYNPPPPPPPPPPPPYYEEEETTTTTTMMMMMMMMYZYYYYYGGGCCOOOOWWWWWWWWAAAATTTTTTTTTBTTTTTJJJJEWWWWWWWWWWWHHHHEDGEEEESSEEEESSESSSFSYYYYYYJJJJJJJJJLZZ
NANNYYYPPPPPPYYYYPYYEEETTTTTTTMMMMMMOOYZYYYYYGGGCCOOOOOWWWWWWWKAAATTTTTTTBBBBBBTTJJJJEWWWWWWWWWWHHHHHGGGGEESSSSSESSSSSSSSSSYYYYYYHJHHJJJJLLL
NANNYYYPPPPPPPYYYYYKEEEETTTTTMMMOMMOOYYYYYYYYKKKKCOOOOOWWWWWWWKAATTTTTTBBBBBBBBBJJJTJWWWWWWWWWWWHHHHHGGGGGGASSSSSSSSSSSSSSYYYYYYHHHHHJJJLLLL
VVEVYYYYYPPPPPYYYYYKEEEETTTTTTTMOOOOOOYFYYYYYKKKKKKKKKKWWWWWWWKKATTTTTTTBBBBBBBBJJJTJWWWWWWWWRRRRRRHHGGGGGGGSSSSSSSSSSSSSSYYYYYYHHHHJJJJLLJL
VVVVYYYYYYPYYFYYKKKKEKKTTTTTTTLMMOOOOOOYYYYYDDKKKKKKKKKWWWWWWWKKAAAZTTQQBBBBBBBBJJJTTLLLLLLLLLLRRRRHHGGGGGGGGGGSSSSSSSSSSSYYYYHYHHHHJJJJJJJJ
VVVVVYYYYYYYYFFYKKKKKKKKKKZZTGMMMMOOOOOCYCCYDDKKKKKKKKKWWWWWWWKAAZZZTTQQBBBBBBBBBBTTTLLLLLLLLLLRRRRGGGGGGGGGGGGSSSSSSSSSSSYYHHHHHHHHJJJJJFJJ
VVVVYYYYYYYFYFFFKKKKKKKKZZZWGGGMMMOOONNCCCCCDKKKKKKKKKKKKKKKAAAAZZZZTTTQBBBBBBNBBTTTTLLLLLLLLLLRRRRGGGGGGGGGGGGSSSSSSSSSFSSSHHHHHHHHHFFFJFFJ
VVVVVVFFYYFFFFFFYYKKKKKEEEZWWGGMMNNNNNFFCCCCDKKKKKKKKKKKKKKKKAAZZZZZZTQQBBBBBNNBBTTTTLLLLLLLLLLRRRRRGGGGGGGGGGGSSSSSSSFFFFSGHHHHHHHHHFFFFFFJ
VVVVVFFFFFFFFFFFKKKKKKKEEEEEEEEEENNNNNFNNCVVVVVVKKKKKKKCCKKKKKAZZZZZZZQBBBBBBNNBTTTTTLLLLLLLLLLRRRRRGGGGGGGGGGSSSSSSLFFFFFFGHHHHHHHHHHFFFFFF
VVVVVFFFFFFFFFFFKKKKKKKEEEEEEEEEENNNNNNNNVVVVVVVVVKYCCKCCCCZKSZZZZZZZZZTTBBBBBBTTTTTTLLLLLLLLLLRRRRRAGGGGGGGGGSSLLLLLFFFFFFFFHHHHHHHHHHFFFFF
VVVVVFFFFFFFFFFKKKKKKKKEEEEEEEEEENNNNVNNNVVVVVVVVVKKKCCCCCZZZZZZZZZZZZZZTBBBTTTTTTTTTLLLLLLLLLLRRRRYNGNNGGGGGSSLLLLLLLFFFFFFFFHHHHHHHHFFFFFF
VVVVVVFFFFFFFFFKKKLLLLLLEEEEEEEEENNNNVNVVVQVVVVVVVCCCCCCCCZZZZZZZZZZZZZZBBBTTTTTTTTTTLLLLLLLLLLRMMNNNNNNNGGGGGGLLLLLLLLLFFFFFFHHHHHHHHFFFFFZ
VVVVVVFFFFFFFFFKKELLLLLLEEEEEEEEEWWNNVVVQQQQQVVCVVCCCCCCZCZZZZZZZZZZZZZZPBBZTTTTTTTTPLLLLLLLLLLMMNNNNNNNNGGGGGGGGGGLLLLLLLFFFFFHHHHHHHFFFFZZ
VVVVVVFFFFFFFFNNKELLLLLLEEEEEEEEEWWWNVVVQQQQQVVCFFCCCCCCZZZZZZZZZZZZZZPPNZZZZTTTTTTTTLLLLLLLLLLMMMNNNNNNNNGGGGGGGGGLLLLLLLFFOAFFHZHZZHFFFFZZ
VVVVVFFFFFFFFFNNZELLLLLLEEEEEEEEEWFFVVVVQQQVVVCCCCCCCCCCZZZZZZZZZZZZZZGPNZZZZTTTTTTTTTPPPYYYYMMMMNNNNNNNNNNNNGGGGLLLLLLLLLFAAAFFHZZZZZZZFZZZ
VVVVVFFFFFFFNNNLLLLLLLLLLEEEEEEEEFFFVVVVVVQKKVCCCCCCCCCCZZZZZZZZZZZZZZGNNZZZZTTTTTTTTYOPMMYYYYMMMNNNNNNMNMMMMMMGGLLLLLLLLLAAAAAAAAZZZZZZZZZZ
VVVFFFFFFFFFNNNLLLLLLLLLLEEEEEWWWFFVVVVVVVQQKVCKCKCCCCCCCZIIZIZZZZFZZGGGNGZZTTTTSTTTTOOOMYYYYYMMMNNMNNMMMMMMMMMLLLLLLLLLLLAAAAAAAAAZAZZZZZZZ
VVVVVVFFFFFNINNLLLLLLLLLLEEEEEWWDFFFFTTVTTTTKKKKKKCCCCCCCCIIIAZZZZFFZGGGGGZZTTTSSSTTTOOMMYYYMYMMMNMMNNNMMMMMMMWOLLLLLLLLLLAAAAAAAAAAAZAZZZZZ
VVVVVVFFJJJNNNNLLLLLLLLLLLEEEEWDDFFFTTTTTTCTKKKKKCCCCCCCCCCAIAAZZZFFFFFFFGTTTTOSOOOQOOOOMMMYMYMMMMMMMMMMMMMIIMWWLWWWWWWLLAAAAAAAAAAAAAAZZZZZ
VVVVVVVFJLLLLLLLLLLLLLLLLLEWWWWDDFFFTTTTTTCTKKKKKKCDBCCCCAAAAAAAAFFFFFEFFFTTTTOOOOOOOOOOMMMMMMMMMMMMNMMMMMMMIIIWWWWWWWLLAAAAAAAAAAAAAAAZZZZZ
VVVVVVVFVLLLLLLLLLLLLLLLLLEWWWWWDFXXTTTTTTTKKKKKKDDDDCCCCCBBAAAFFFFFFEEEEFFFMCOOOOOOOOOOOMMMMMMLLLNNNNNNNNRNIIIWWWWWWWWAAAAAAAAAAAAAHAWWZZZZ
VVVVVVVVVLLLLLLLLLLLLELLLEEWWWWWWYXYTTTTTTTTKKKKKKDDDDDCDBBAAAAFFFFFEEEZEFFFMOOOOOOOOOOOOMMMMKKLLNNNSNNNNNNNNNNWWWWWWWWAAAAAAAAAAAAAAAWWZZWZ
VVVVVVVVXLLLLLLLLLLLLELLLEENWWYYYYYYTSTTTTTKKKKKKHIDDDDDDBAAAAAAFAFFEEEEYMMMMMNNOOOOOOOOOXMMKKKLLLNNNNNNNNNNNNWWWWWWWWWWAAAAAAAAAAAAAAWWWWWZ
VVVVVVVVWLLLLLLLLLLLLJLLLNNWWWWYYYYYYYTTTTTKKKKKHHHDDDDDDBAAAAAAAAEFEEEMMMMMMMMMOOOOOOOOXXXXOKKKKLLLNNNNNNNNNWWWWWWWWWWAAAAAAAAAAAAAWWWWWWZZ
VVVVVVWWWLLLLLLLLLLLLJLLLNWWWWWYYYYYYTTTTTOOOOOKHHHHDDDDKAAAAAAAAZEEEEEMMMMMMMMMMOOOOOOOYXBKKKKKKLLNNNNNNNNNNWWWWWWWWWWAAAAAAAAAAAAWWWWWWWWW
VVAVVVWWWWWWWLLLLLLLLJLLLRWRWWWYYYYYYYTTTFOOOOOOOHHNBBDDAAAAAAAAAEEEEEEERMMMMMMMMOOOOOXOXXXKKKKKKLLLNNNNNNMWWWWWWWWWWWWWWDDDAAAAWWWWWWWWWWWZ
AAADVVWWVWWWWWJJJJJJJJJNRRRRRRYYYYYYYYTTFFTOOOOOONNNBBDAAAAAAAAAAWEEEEEMMMMMMMMMMMOOOOXXXXXKKKKKKNNNNNNNNMMWWWWWWWWWWWWWWWDAAWWWWWWWWWWWWWZZ
AAAAAAAAWWWWWWWWWJJJJJJRRRRRRRRYYYYYYYTTTTTTOOOODBBBBBBBAAAAAAAARWEEEEEMMMMMMMMMMMMXXXXXXXOKKKKKKKKNNNNNNNYWYYWWWWWWWWWCWDDWAWWWWWWWWWWWWWWZ
AAAAAAAAZWWWWWWWJJJJJJJRRRRRRRRRYYYYYYYGGTKKKOOBBBBBBBBBAAAHHAARRRRRRRRMMMMMMMMMMMMXXXXXXXOKKKKKKKKENNNNNNYYYYWWWWWWWWWWWWDWWWWWWWWWWWWWWWZZ
AAAAAAAAWWWWWWWWJJJJRRRRRRRRRRRRYRRRYYYGGGGOOOOBBBBBBBBBBAHAAASRSRRRRRRMMMMMMMMMMMMMXXXXXXXXXKKKKKKKNNYYNYYYYWWWWWWWWWWWWDDWWWWWWWWWWWWWWWWW
AAAAAAIAAWWWWWWWJJJJJRRRRRRRRRRFFRRFGGGGGGGPPPBBBBBBBBBBBHHHHHSRSRKRRRRRRMMMMMMMMMMMMMXXXXXXXKKKKKKKKYYYYSSSSDFWWWWWWWWZRDWWWWWWWWWWWWWZZWWW
AAAAAAAAAAWWWWWWJJJJJRRRRRRRRRRFFRFFGGGGGGGPPPPBBBBBBJBBBHHHHHSSSRRRRRRRRRMMMMMMMMMMXXXXXXXXXXKKKKKKKYYYDSSSSDFFFFRWRWZZRJJWJWWWWWWWWWWWZZZZ
AAAAAAAAAWWWWWWWJJJJJRRRRRRRRFFFFFFFFGGGGGGGGPPBBBBBBBBBBHHHHHSSRRRRRRRRRRRRRMMMMMMMXXXXXXXXKKKKKKKKKSSSSSSSSDFRRRRRRWRRRRJJJWWJWWWWWWWWWZZZ
ZZAAAAAAAWZWWWWWWJJJRRRRRRRRRFFFFFFFFGGGGGPPPPPBBBBBBBBHBHHHHHRRRRRRRRRRRRRRRMMMMMTMXXXXXXXXKKKKKKKYKSSSSSSSSDDDRRRRRRRRRRRRJJJJJWWJJJJWZZZZ
ZZAAAAAAAWZZWWWWWWJJRRRRRRRFFFFFFFFFGGGGGGGGPPPPBBBBBBBHHHHHHHHRRRRRRRRRRRRRRMMMXXXXXXXXXXXXXXKKKKKYYSSSSSSSSDDDDRRRRRRRRRRRRJJJJJJJJJJZZZZZ
ZZZAZZAAZZZZZWWJJJJJRRRRRRFFFFFFFFFFFFGGGGGPPPPBBBBBBBPHHHHHHHHHRRRRRRRRRRRRRRRRXXXXXXXXXXXXXXKKKKYYYSSSSSSSSDDDDEEERRRRRRRRRRJJJJJJJJJZZZZZ
ZZZZZZAAZZZZZWJJJJJJJRJRRRJFFFFFFFFFFGGGGPPPPPPBBBBBBBBHHHHHHHRRRRRRRRRRRRRRRROXXXXXXXXXXXXXXXXXXXXYYYDDDSSSSDDDDEEERRRRRRRRRJJJJJJJJJJZZZZZ
ZZZZZZZAZZZZZWJJJJJJJRRRRRJJJFDFFFFFBGGGWWWPPWPBBBBBHHHHHHHHHHHRRRRRRRRRRRRRRROOXXXXXXXXXXXXXXXXXXYYYYDSSSSSSDDDDEEEERRRRRRLLLLLLJJJJJJZZZZZ
ZZZZZZZZZZZZZWWJJJJJJJJRRRJJJFFFFFFBBGWWWWWWPWWBRBBBBBHHHHHHHHHRRRRRRRRRRRRRRROOXXXXXXXXXXXXXXDDDDDDYYDSSSSSSDDDEEEEERRERRRLLLLLLJJJJJJZZZZZ
ZZZZZZZZZZZZZWPPPPJJJJJJJJJJJJFFGFFFFFWWWWWWWWWRRBBBBBHHHHEEHHHRHHRRRNRNNVRRVVVVVVXXXXXXXXXXXXXDDDDDDFFSSSSSSDDEEEEEEEEERRLLLLLLLLLLLLJZZZZZ
ZZZZDDDZZZZZZWPPPKJJJJJJJJJJJGGGGGFFIIIWWWWWXWWWBBBBBBHHHHEEHHHHHHRRRNNNNVVVVVVVVVYYXXXXXXPOXXXDDDDDDDFSSSSSSDFFFEEEEEEELRLLLLLLLLLLLLZZZZZZ
ZZZDDDZZZZZQQPPPPKJJJJJJJJJJJJJGGGGIIIIWWWWWWWWWBBBBBBQQQEEHHHHHHKKRNNNNJVVVVVVVVYYXXXXXXKPOOODUUUUUUUUSSSSSSFFFEEEEEEEELRLLLLLLLLLLLLJZZZZZ
ZZZZDDZZZZZQPPPPPPJJJJJJJJJJJJGGGGGIIIIWWWWWWWAWJBBBBBQQQEEEUHHKKKNRRNNNNNLVVVVVVYYXXXPPPPPPOODUUUUUUUUSSSSSSFIFEEEEEEEELLLLLLLLLLLLLLZZZZZZ
ZZDDDDRRZPPPAPPPPPPPPPPPJJJJJJGGGGGGGIIWWWWWWWAWWFBBMMEEEEEEEHHKKNNNNNNNNNNVRVVVVVXXWXPPPPPPPOOUUUUUUUUSSSSSSIIEEEEEIEEEILLLLLLLLLLLLLZZZZZZ
ZDDDDDDRPPPPPPPPPPPPPPPPJJJXXJXXGGGGXPPPWWWWWWAAAFFFMMEEEEEEEHDNNNNNNNNNNNWVVVVVVVWXWPPPPPPPPPOUUUUUUUUSSSSSSIIIIIIIIIIIILLLLLLLLLLLLLZZZZZZ
DDDDDDDDBPPPPPPPPPPPPPPPJJJJXXXXXGGGXMPPWWWWWWAAAAFMMMMEEEEEEEENNNNNNNNNNNWWVWVWVWWWWPPPPPPPPOOUUUUUUUUSSSSSSIIIIIIIIIIIILLLLLLLLLLLLLZZZZZZ
DDDDDDDDDPPPPPPPPPPPPPPPJJJJXXXXXXGMMMRPPWWWWAAAAMMMMMMMMEEEEEEXNNNNNNNNNWWWWWWWWWWPPPPPPPPPPPPUUUUUUUUUUUUUUUIIIIIIIIIIILLLLLZZJZZJZZZZZZZZ
DDDDDDDDDYDPPPPPPPPPPPPPJJXXXXXXXXXPMMXWWWWWWAMCAMMMMMMMMEEEEEXXXNNNNNNNGGWWWWWWFWWWPPPPPPPPPPPUUUUUUUUUUUUUUUIIIIIIIIIIIIILLLLZZZZZZZZZZZZZ
DDDDDDDDDDDPPPPPPPPPPPPPJXXXXXXXXXXXKXXWWWWWWWWCMMMMMMMMMEEEEEEXXXNNNNNGGGGWWWFFFFFWPPPPPPPPPPPUUUUUUUUUUUUUUUIIIIIIIIIIIIMMMMMMZZZZZHHZZZZZ
DDDDDDDDDDDPPPPPPPPPPPPPJXXXXXXXXXXXXXXWXWWWWWWCCCMMMMMMMMEEEEEXXXNGGGNGGGGGWWFFFFFFFPPPPPPPPPPUUUUUUUUKFUUUUUIIIIIIIIIMIMMMMMMZZZZZZHHHHHHZ
DDDDDDDDDDTHPCPPPPPPPPXXXXXXXXXXXXXXXXXWXXXXXXXCCCCMMMMHHHEEEEEXXXFGGGGGGGGGGFFFFFFFFPFPPPPPPPIUUUUUUUUKFUUUUUIIIIIIIIIMMMMMMMMMMMZZHHHWHHHH
DDDDDDDDDDDHHHPPPPIPPPXXXXXXXXXXXXXXXXXXXXXXXXXCCCCMMHMHHHHEEEEXFFFGGGGGGGGEEEFFFFFFFFFPPPPPPPIIIUUUUFKKKUUUUUIIIIIJIEIMMMMMMMMMMMMMFHHHHHHH
DDDDDDDDDHHHHHHPIIIIIIXXXXXXXXXXXXXXXXXXXXXCCCCCCCCMMHHHHHHHHHFFFFFFGGGGGGEEEEFFFFFFFFFPPPPPPPPIIUUUUKKKKKKKKIIIMIMMIIMMMMMMMMMMMMMMHHHHHHHM
DDDDDDDDDHHHHHPPPIIIIIXXJJXXXXXXXHXXXXXXXXXCCCCCCCCVAHHHHNNNNNNNNNNFGGGGGXKEEEFFFFFFFFFPPPPBIIIIIUUUUKKKKKKKKMMMMIIMMMMMMMMMMMMMMMMMHHHHHHHH
DDDDDDDDDHHHHHIIIIIIIIXXOOOXXXXXXHHRQXXXXXGCCCCCCCCAAAHHHNNNNNNNNNNNNNNGIKKKEEFFFFFFFFFFFPCIIIIIIUUUUKKKKKKKKKMMMBMMMMMMMMMMMMMMMHHHHHHHHHHH
DDDDDDDDHHHHHHHHHHIIIIIOOOOXXXXXXHRRQXXXXXGCCCCCCCCCAAAAHNNNNNNNNNNNNNNKKKKKKFFJJFFFFFFFFNIIIIIIIUUUUKKKKKKKMMMMBBBBBMMMMMMMMDMMHHHHHHHHHHHH
DZDDDDDHHHHHHHHHHHHIIIIIOOOOXXOOOHRRRRXXXXCCCCCCCCCAAAAAANNNNNNNNNNNNNNKKKKKKKFFJFFFFFFFFNNNIIIIIKKKKKKKKKKKMMMBBBBBBBMMMMDDVDMMHHHHHHHHHHHH
HZDDHDDHHHHHHHHHHIIIIIIIOOOOOOOOOORRRXXXNCCCCGCCCCCAAAAAANNNNNNNNNNNNNNKKKKKKKKKKOOOFFFFNNNNIIIIIIKKKKKKKKKKMMMBBBBBBBMMMMDDDDDDDDDDHHHHHHHH
HHHHHLLHHHHHHHHIHIIIIIIIOOOOOOOOOORMRRXXXCCCCCCCCCAAAAAAANNNNNNNNNNNNNNKKKKKKKKKJOOFFFFFNNNNIIIIIIIKKKKKKKKKMMMBZBBBBMMMMMDDDDDDDDDHHHHHHHDH
BBBHAHHHHHHHHHHIIIIIIIQQOOOOOOOOOOOMRQQQCCCCCCCCCAAAAAAAANNNNNNNNNNFFFKKKKKKKKJJJOFFFFFFFFNCCIIIIKKKKKKKKKMMMMMBBBBBBMMMDDDDDDDDDDDHHHHHHDDD
BBBHHHHHHHHHHHIIIIIIIPIQQOOOOOOOOORRRQQQCCCCCCCCCCCAAAAAANNNNNNNNNNFFJJKJKKKKJJFFFFFFFFFFFNCCCCIIIKKKKKKKKKKMLBBBBBBBBBTDDDDDDDDDDDHHHHHDDDD
BBBBBBHHHHHHHHHIIIIIIIIQQQOOQOQQQQQQQQQQCCCCCCCCCCCCAAAAANNNNNNNNNNJJJJJJKJKKJJJSFFFFFFFFFFFCCIIIKKKKKKKKKKKMLLLLBBBBBBBDDDDDDDDDDDDDDDDDDDD
BBBBBBBBHHIIIHIIIIIIIIIQQQQOQOQQQQQQVQCCCCCCCCCCCCCCAAAAANNNNNNNNNNJJJJJJJJJJJJJFFFFFFFFJFFFCCICIIIIKKUKKKKKLLLLLBBBBBBDDDDDDDDDDDDDDDDDDDDD
BBBBBBNHHNNIIIIIIIIITTQQQQQQQQQQQQVVVCCCCCCCCCCCCCCCAAAAAAAAAARRRRRJJJJJJJJJJJJJFFFFFFFFFFCCCCCCIIIUUUUKKKKLLLLLLLBBBBBZDDDDDDDVVDVDDDDDDDDD
BBBBBNNNNNNNNIIIIIIITTTQQQQQQQQQQVVVVVVVCCCCCCCCCCCXXAAAAAAAARRRRRJJJJJJJJJJJJJJPPFFFFFFWFCCCCCCCCCVVUUUUUUULLLLLLLLBKBDDDDDDDVVVDVVDDDVDDDD
BBBBNNNNNNNNIIIIIIIITTTTHHQQQQQQQQVVVVVVVVVCCCCCCCCCXAAAAAAARRRRRRRRJJJJJJJJJJJJPFFPPFFFCCCCCCCCCCCVVVMMUUULLLLLLLLLLLLDDDDDVVVVVVVVVVVVDDDD
BNNNNNNNNNNIIIIIIIIITTTTTHQQQQQQQVVVVVVVVVVVCVVCCCCKKKAAAAAAAARRKRRRJJJJJJJJJJJJPPFFPFFFCCCCCCCCCCRMMMMMUUUUULLLLLLLLLLLYDDVVVVVVVVVVVVVVVDD
BNNNNNNNNNNENIIIIIITTTTTTHQHQQQQQVVVVVVVVVVVVVVCVVCKKKKKKAAGKKKKKRRJJJJJJJJJJJJJJPPPPFFCCCCCCCCCCCMMMMMMMBMUMMLLLLLLLLYYYDYYVVVVVVVVVVVVVVDD
BNNNNNNNNNNNNIIIIIIIITTTTHHHHYYQQQQVVVVVVVVVVVVVVVCCKKKKKKAKKKKKKRRJJJJJUUJJJJJJJJPPPPFCCCCCCCCCCCMMMMMMMBMMMKLLLLDDDDDDDDYYVVVVVVVVVVVVVDDD
BNBBNNNNNNNNNNIIIIIIIIFTHHHYYYYQQQQVVVVVVVVVVVVVVVCCVVKKKKKKKKKKKRRRUUUJUUUJJJJJPPPPPXTCCCCCCCCCEMMMMMMMMMMMBLLLLLDDDDDDDDYVVVVVVVVVVVVVVVDD
BBBBNNNNNNNNNNIIIIIIIIFFHHHHHHQQQQLLLLLVLVVVVVVVVVVVVKKKKKKKKKKKKRUUUUUUUUUJJJJJJPXXXXTTCCCCCCCCCMMMMMMMMMMMBLLLLLDDDDDDDDYVVVVVVVVVVVVVVVVV
BBBBBNNNNNNNNNIINIIIIIFHHHHHHQQQQQQLLLLLLVVVVVVVVVVKKKKVKKKKKKKKKKJUUUUUUUUJJJJJJPPPXXXTCCCCCCCCCCMMMMMMMMMBBLLLJLDDDDDDDDYSSVVVVVUVVVVVVVVV
BBBNNNNNNNNNNNNNNNIIIFFHJJJJJJJJJJQLLLLLLLVVVVVVVVVVVKKKKKKKKKKKKUUUUUUUUUUUULLLJPLXXXXXAACCCCCCCCMMMMMMMMMBLLLLLLDDDDDDDDSSVVVVVVUVVVVVVVVC
BBBNNNNNNNNNNNNNNRRRFFFHJJJJJJJJJJLLLLLLLLVVVVVVVVVVKKKKKKKKKKKKKUUUUUUUUUUUUULLLLLXXXXXXACCCCCDCCAMMMMMMMMMLLSSLLDDDDDDDDSVVVVVVUUVVUCCUCCC
BBBNNNNNNNNNNNNNRRRRRHHHJJJJJJJJJJLLLLLLLJJVVVVVVVVKKKKKKKKKKKKKKUUUUUUUUUUUUULLLLXXXXXXXAACEEEUUUUUMUUMMMUUULUSSSDDDDDDDDDDVVVVVUUUVUCCUCCC
BBBBYYNNNNNNNNNNRRRRRRHHJJJJJJJJJJLLLLLLLJGTGVVVVVKKKKKKMKKKKKKKUUUUUUUUUUUUUULLLLXXXXXAAARRRREUUUUUUUUUUUUUUUUUSSSSSSSDDDDDVEVVVUUUUUUUUUCC
BBBBBYNNNNNNNNNCFRRCRRHAJJJJJJJJJJLLLLGGGGGGGJKVKKKKMMMMMKKKKKKKUUUUUUUUUUUUUULLLLLXXXXAARRRRUUUUUUUUUUUUUUUUUUUSSSSSSSDDDDDEEVVUUUUUUUUCCCC
BYYYYYYYNNNNNNNCCCCCRRRHJJJJJJJJJJLLLGGGGGGGGGKVKKKKMMMMMMMMKKKKUUUUUUUUUUUUUUUXXXXXXXXRRRRRRRUUUUUUUUUUUUUUUUSSSSSSSSSDDDDDEEVIUUUUUUUUUUCC
BYYYYYYYYYYNNNNCCCCCCRRRJJJJJJJJJJLLLWGWGGGGGKKKKMMKKMMMMMMMMKKKUUUUUUUUQUUUUUUXXXXXXXXXXRRRRRUUUUUUUUUUUEEUUUSSSSSSSSSSSSSSSEUUUUUUUUUUUUUC
BYYYYYYYYYXONNNCCCCCCCRRJJJJJJJJJJLWWWWWGGGGKKKKKMMKMMMMMMMMMMKKUUUUUUUQQQQUUXXXXXXXXXXRRRRRRRRRRUUUUUUUUEEUEUSSSSSSSSSSSSMMMUUUUUUUUUUUUUUU
YYYYYYYYOOOONNCCCCCCCDDDDDGJJJJJJJLWWWWGGCCCKKKKKKMMMMMMMMMMMKKKKSUUUXEEEEEENXEXXXXXXXXRRRRRRRRRUUUUUUUEUUEEEEESSESESSSMMMMMMMMUUUUUUUUUUUUG
YYYYYYYYOOOOOCCCCCCCCDDDCCGJJJJJJJWWWWWWWWCCCKKKKMMMMMMMMMMMMKKKKSSUXXEEEEENNEEEEXXXXXRRRRRRRRRRUUUEEEEEEEEEEEEESEEEEMMMMMMMMMMUUUUUUUUUUUUG
GYYYYYYXOOOOOOCCCCCCCCDDCCGGGGGGGGWWWWWWWWWCCKKFKMMMMMMMMMMMMMKKKKSSEEEEEEEEEYEEXXXXXRRRRRRRRRRRUUEEEEEEEEEEEEEEEEEEMMMMMMMMMMMUUUUUUUUUUUGG
GYYYOTYOOOOOOSOCCCCCCCCCCCGGGGGGGWWWWWWWWWCCZZZFFMDMMDDDDMMWWKKKRLLEEEEEEEEEEEEEXXXXXXXXRRRRRRJJUJJJJEEEEEEEEEEEEEEEMMMMMMMMMFUUUUUUUUUUUUGG
GGGOOOOOOOOOOOOOCCCCCCCCCCCCGGGGGGWWWWWWWCCCZZZFDADDMMDDDMWWLLKKKLLEEEEEEEEEEEEEEEXXXXRRRRRRRRRJJJJJJEEEEEEEEEEEEEEMMMMMMMMMMFGGGGGUGUUUJJJG
GGGGOOOOOOOOOOOOCCCCCCCCGGGGGGGGGGWWWWWEZZZZZZZFDDDMMDDDDDDLLLKKLLLEEEEEEEEEEEEEEEEXXRRXRRRRRRRRRJJJJJJEEEEEEEEEEEEEEMMFFFFFFFGGGGGGGUGGJJGG
GGGOOOOOOOOOOOCCCCCCCCCCCGGGGGZGGZWWWWWEZZZZZZZDDDDDDDDDDDULLLLKLLLLEEEEEEEEEEEMEXEXXXXXRLRRRRRRRJJJEJENNEEEEEEEEEEEEMMFFFFFFFFGGGGGGGGGJGGG
GGGGOOOOOOOOOOOCCCCCCCCCGGGGGGZZZZZWWWWWZZZZZZZZDDDDDDDDDDUULLLLLLLEEEEEEEEEEEEEXXEXXXXXXXRRRRRMEEEJEEENEEEEEEEEEEEEEMMFFFFFFAAGGGGGGGGGGGGG
GOGGOOOOOOOOOOOOCCCCCCCCGGGGGGGGZZZWWWWEZZZZZZZDDKDKDDDDDDLLLLLLLLEVEEEEEEEEEEEEXXXXXXGGXGGYGRMMEEEEEEEEEEPEEEEEEEEELFFFFFFFFFAGGGGGGGGGGGGG
OOOOOOOOOOOOOOOOCCCCCCTCGGGGGGGZZZZWWWZZZZZZZZZZDKKKDDDEEEELLLLLLLEEEEEEEEEEERRXXXXXXXXGGGGGGBEEEEEEEEEEEEEEEEEEYEEEEEFFFFFFFYGGGGGGGGGGGGGG
QQOOOOOOOOOOOOOTTTCTTCTCTGGGGGZZZZZZWWZZZZZZZZZZKKVVVHDCEEKLLLLLCCCECECEEEEEERUUNMMMMMGGGGGXEEEEEEEEEEEEEEEEEEEEYEFFFFFFFFFFGGGGGGGGGGGGGGGG
QKOOOOOOOOOOTOTTTTTTTTTTTGGGGGZZZZZZZZZZZZZZZZZZZVVVVVVCEEEEEEEECCCECCCCEEEEEUUUNNMMMMMMGGGXXEEEEEEEEEEEEEEEUEEEEEFFFFFFFFFFFGGGGGGGGVGGGGGG
QKKOOOOOOOTTTTTTTTTTTTTTTTTTTWWZZZZZZZZZZZZZZZZZMVVVVVVVVEEEEECEUCCCCCCCEUNEUUUUUUMMMMMGGGXXXLLEEEEEEEEEEEEEEMMZZZFZFFFFFFFFFGGGGGGGGGGLGGGG
QKKKKKKKKTTKTTTTTTTTTTTTTTTTPWZZZZZZZZZZZZZZZPZHVVVVVVVVVEEEEVCCCCCCCCCCEUUUUUUUUMMMMMMGXXXXLLLEEEEEEEEEEEEEMMZZZZZZFFFFFFFFFGGGGGGGGGGGGGGG
KKKKKKKKKKTTTTTWWTWTTWWTTTTTTWZZZZZZZZZZZZVPQPHPPVVVEVVVEEEEEEEECCCCCCCCCCUUUUUUUFFFMMMWMXLLLLLLLLEEEEEEEEEMMZZZZZZZFFFFFFFFFGGNGGGGGGGGGGGG
KKKKKKKKKKTTTTTWWWWWWWWWTTTTWWZZZZZZZZZPPPPPPPPPPEVVEVEEEEEEEECCCCCCCCCCCCUMUUUUUUMMMMMMMLLLLLLLLLLEEEEEEEMMMMZBZZZZZZFFFFFFFFFGGGGGGGGGGGGG
KKKKKKKKKKTTTTTWWWWWWWWWWWWWWWWZZZZZZZZPPPPPPPPPPEEEEEEEEEEEEECCCCCCCCCCCCUMMUUUUUMMMMMLLLLLLLLLLLLLEEEEEEEEMMZZZZZZZZZFFFFFFFFFGGGGGGGGGGGG
VKKKKKKKKKTTWWWWWWWWWWWWWWWWWWWWZZZZZZZPPPPPPPPPPEEEEEEEEEEEECCCCCCCCCCCCCMMMMUMUUFFMMMLLLLLLLLLLLLLEEEEEEMMMZZZZZZZZZZFFFFFFFFFGGGGGGGGGGGG
KKKKKKWWWTTWWWWWWWWWWWWWWWWWWWWWZZWWWZZPPPPPPPPPEEEEEEEEEEEEEECCCCCCCCCCCCCMMMMMOFFFMLLLLLLLLLLLLLLAEEEEEEMMMMZZZZZZZZFFFLLLFFFFGGGGGGGGGGGI
KKKKKKKWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWPPPPPPPPPPEEEEEEEEEEEEEEEECCCCCCCCCCCCCMMMOFFFMLJLLLLLLLLLLLLAAAVMEEEMMMMZZZZZZZZFFLLLFFFFFFGGGGGGGIGI
KKKKKKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPEEEEEEEEEEEEEEEEEECCCCCCCCCCOOMOOOFOOMJJLLLLLLLLLLLLLAVVVVMMMMMZZZZZZZZFFELLLLFFFFFFGGGIGIIII
KKKKKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPWPPPPPEEEEEEEEEEEEEEEEEEECCCCCCCFCCOOOOOOOOOOJJLLLLLLLLLVVLLAVVVVMMMMMZZZZZZZZZFELLLLFFFFFIIGGIIIIII
KKKKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPDDPEEEEEEEEEEEEEEEEEEEECCCCCCFCXOOOOOOOOOJJJJLLVLLVVLVLLLVVVVVMMMMMMMMZZZZZZZEELLLFFFFIIIIIIIIIII
KKKWWWWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEECCCCCCCNOOOOOOOOOOJJJJJLVVVVVVVVVVVVVVVMMMMMMMMMMZZZZEEEEELFFIIIIIIIIIIIII"""


class Section():
    def __init__(self):
        self.locations = []


    def __repr__(self):
        return str(self.locations)


    def add_location(self, x, y):
        self.locations.extend([(x, y)])

    def find_unique(self):
        return list(set(self.locations))


class Grid():
    def __init__(self, data):
        self.map = [[s for s in r] for r in data.split('\n')]
        # print(self.map)
        self.checked = []
        self.sections = []
        self.height = len(self.map)-1
        self.width = len(self.map[0])-1

    def __repr__(self):
        v = ''
        for c in self.grid:
            for r in c:
                v += r
            v += '\n'
        return v

    
    def _valid_move(self, x, y, value, dct):
        dx = dct[0]
        dy = dct[1]
        if x == 0 and dx == -1:
            return False
        if y == 0 and dy == -1:
            return False
        if x == self.width and dx == 1:
            return False
        if y == self.height and dy == 1:
            return False
        # if (x+dx, y+dy) in self.checked:
        #     return False 

        return self.map[y + dy][x + dx] == self.map[y][x]
        

    def find_section_perimeter(self, x, y, section):
        # print(x, y)
        if (x, y) in self.checked:
            return
        else:
            for move in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
                dx = move[0]
                dy = move[1]
                value = self.map[y][x]
                if self._valid_move(x, y, value, move):
                    self.checked.append((x, y))
                    section.add_location(x, y)
                    if (x+dx, y+dy) not in self.checked:
                        self.find_section_perimeter(x+dx, y+dy, section)
                    

        
        # self._check_adj(x, y, value)
    def create_section(self):
        for y in range(self.width+1):
            for x in range(self.height+1):
                if (x, y) not in self.checked:
                    # print(self.map[y][x])
                    section = Section()
                    section.add_location(x, y)
                    self.find_section_perimeter(x, y, section)
                    self.sections.append(section.find_unique())


grid = Grid(farm_map)
grid.create_section()

def borders(location, section):
    default = 4
    for move in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
        if (location[0] + move[0], location[1] + move[1]) in section:
            default -= 1 
    return default


def find_perimeter(section):
    perim = 0
    for l in section:
        perim += borders(l, section)

    return perim


def add_coord(line_id, search_dir, value, x, y, dx, dy):

    if search_dir == 'row':
        if y != line_id:
            return False
        if dy == -1:
            if y == 0: 
                return True 
        if dy == 1:
            if y == grid.height:
                return True
    elif search_dir == 'col':
        if x != line_id:
            return False
        if dx == -1:
            if x == 0: 
                return True
        if dx == 1: 
            if x == grid.width:
                return True
    
    if grid.map[y+dy][x+dx] == value:
        return False
    return True


def find_top(section, value):
    count = 0
    for y in range(grid.height+1):
        x_values = [s[0] for s in section if add_coord(y, 'row', value, s[0], s[1], 0, -1)]
        sort_x = sorted(x_values)
        for i in range(len(sort_x)):
            if i == 0:
                count += 1
            else:
                if sort_x[i] != sort_x[i-1] + 1:
                    count += 1
    
    # print("top", count)
    return count


    return 1


def find_bottom(section, value):
    count = 0
    for y in range(grid.height+1):
        x_values = [s[0] for s in section if add_coord(y, 'row', value, s[0], s[1], 0, 1)]
        sort_x = sorted(x_values)
        for i in range(len(sort_x)):
            if i == 0:
                count += 1
            else:
                if sort_x[i] != sort_x[i-1] + 1:
                    count += 1
    
    # print("bottom", count)
    return count


def find_left(section, value):
    count = 0
    for x in range(grid.width+1):
        y_values = [s[1] for s in section if add_coord(x, 'col', value, s[0], s[1], -1, 0)]
        sort_y = sorted(y_values)
        for i in range(len(sort_y)):
            if i == 0:
                count += 1
            else:
                if sort_y[i] != sort_y[i-1] + 1:
                    count += 1
    
    # print("left", count)
    return count
    
def find_right(section, value):
    count = 0
    for x in range(grid.width+1):
        y_values = [s[1] for s in section if add_coord(x, 'col', value, s[0], s[1], 1, 0)]
        sort_y = sorted(y_values)
        for i in range(len(sort_y)):
            if i == 0:
                count += 1
            else:
                if sort_y[i] != sort_y[i-1] + 1:
                    count += 1
    
    # print("right", count)
    return count

# day1
# day1_cost = 0
# for section in grid.sections:
#     day1_cost += len(section) * find_perimeter(section)

#day2
cost = 0
for section in grid.sections:
    # print(section)
    lines = 0
    value = grid.map[section[0][1]][section[0][0]]
    # print(value)
    lines += find_top(section, value)
    lines += find_bottom(section, value)
    lines += find_left(section, value)
    lines += find_right(section, value)
    cost += lines * len(section)
    # print("sides :", cost)

print(cost)        

# print(day1_cost)